# Generated by Django 4.1.13 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
        migrations.AlterField(
            model_name='table',
            name='guest',
            field=models.CharField(max_length=100),
        ),
    ]
